name: Oxidizer
description: The most powerful oxidizing agent - oxidizes everything and fuses all plugins together! Oxidizer is an API plugin like Vault in Bukkit except that it aims on not only supporting existing plugins but also infinite unknown plugins.
author: LegendsOfMCPE Team
main: oxidizer\Oxidizer
version: 1.0.0
api: [1.11.0]
website: https://github.com/oxidizer/Oxidizer
