---
#
#   _____          _     _ _
#  / ___ \ __   __(_) __| (_)____ ___ _ ___
# | /   \ |\ \_/ /| |/ /| | |_  // _ | v __)
# | \___/ |/ _  / | | ()| | |/ /|  __| /
#  \_____//_/ \_\ |_|\__/\|_|____\___|_|
#

chat:
  format: %prefix%%player%%suffix%> %message%
...
